# Generated by Django 5.0.6 on 2024-07-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_cor_options_veiculo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cor",
            old_name="descricao",
            new_name="nome",
        ),
    ]
